# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(647, 405)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/raw/pics/pardusman.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushBrowseRepository = QtWidgets.QPushButton(self.frame)
        self.pushBrowseRepository.setObjectName("pushBrowseRepository")
        self.gridLayout.addWidget(self.pushBrowseRepository, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.pushBrowseWorkFolder = QtWidgets.QPushButton(self.frame)
        self.pushBrowseWorkFolder.setObjectName("pushBrowseWorkFolder")
        self.gridLayout.addWidget(self.pushBrowseWorkFolder, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineRepository = QtWidgets.QLineEdit(self.frame)
        self.lineRepository.setObjectName("lineRepository")
        self.gridLayout.addWidget(self.lineRepository, 2, 2, 1, 1)
        self.pushBrowsePluginPackage = QtWidgets.QPushButton(self.frame)
        self.pushBrowsePluginPackage.setObjectName("pushBrowsePluginPackage")
        self.gridLayout.addWidget(self.pushBrowsePluginPackage, 4, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.lineWorkFolder = QtWidgets.QLineEdit(self.frame)
        self.lineWorkFolder.setObjectName("lineWorkFolder")
        self.gridLayout.addWidget(self.lineWorkFolder, 5, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboCompression = QtWidgets.QComboBox(self.frame)
        self.comboCompression.setObjectName("comboCompression")
        self.comboCompression.addItem("")
        self.comboCompression.addItem("")
        self.comboCompression.addItem("")
        self.comboCompression.addItem("")
        self.gridLayout.addWidget(self.comboCompression, 6, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.comboType = QtWidgets.QComboBox(self.frame)
        self.comboType.setObjectName("comboType")
        self.comboType.addItem("")
        self.comboType.addItem("")
        self.comboType.addItem("")
        self.comboType.addItem("")
        self.comboType.addItem("")
        self.gridLayout.addWidget(self.comboType, 6, 2, 1, 1)
        self.lineParameters = QtWidgets.QLineEdit(self.frame)
        self.lineParameters.setObjectName("lineParameters")
        self.gridLayout.addWidget(self.lineParameters, 1, 2, 1, 2)
        self.lineTitle = QtWidgets.QLineEdit(self.frame)
        self.lineTitle.setObjectName("lineTitle")
        self.gridLayout.addWidget(self.lineTitle, 0, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.linePluginPackage = QtWidgets.QLineEdit(self.frame)
        self.linePluginPackage.setObjectName("linePluginPackage")
        self.gridLayout.addWidget(self.linePluginPackage, 4, 2, 1, 1)
        self.pushBrowseConfigFiles = QtWidgets.QPushButton(self.frame)
        self.pushBrowseConfigFiles.setObjectName("pushBrowseConfigFiles")
        self.gridLayout.addWidget(self.pushBrowseConfigFiles, 3, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineConfigFiles = QtWidgets.QLineEdit(self.frame)
        self.lineConfigFiles.setObjectName("lineConfigFiles")
        self.gridLayout.addWidget(self.lineConfigFiles, 3, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.terminalLayout = QtWidgets.QVBoxLayout()
        self.terminalLayout.setObjectName("terminalLayout")
        self.gridLayout_5.addLayout(self.terminalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 647, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuiso = QtWidgets.QMenu(self.menubar)
        self.menuiso.setObjectName("menuiso")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/raw/pics/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/raw/pics/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/raw/pics/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/raw/pics/document-save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon4)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/raw/pics/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon5)
        self.actionExit.setObjectName("actionExit")
        self.actionUpdateRepo = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/raw/pics/view-refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdateRepo.setIcon(icon6)
        self.actionUpdateRepo.setObjectName("actionUpdateRepo")
        self.actionPackages = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/raw/pics/applications-other.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPackages.setIcon(icon7)
        self.actionPackages.setObjectName("actionPackages")
        self.actionRootImagePackages = QtWidgets.QAction(MainWindow)
        self.actionRootImagePackages.setIcon(icon7)
        self.actionRootImagePackages.setObjectName("actionRootImagePackages")
        self.actionLanguages = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/raw/pics/applications-education-language.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLanguages.setIcon(icon8)
        self.actionLanguages.setObjectName("actionLanguages")
        self.actionMakeImage = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/raw/pics/media-optical.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMakeImage.setIcon(icon9)
        self.actionMakeImage.setObjectName("actionMakeImage")
        self.actionLivecdImagePackages = QtWidgets.QAction(MainWindow)
        self.actionLivecdImagePackages.setIcon(icon7)
        self.actionLivecdImagePackages.setObjectName("actionLivecdImagePackages")
        self.actionDesktopImagePackages = QtWidgets.QAction(MainWindow)
        self.actionDesktopImagePackages.setIcon(icon7)
        self.actionDesktopImagePackages.setObjectName("actionDesktopImagePackages")
        self.action = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/raw/pics/folder-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon10)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/raw/pics/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_2.setIcon(icon11)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setIcon(icon9)
        self.action_3.setObjectName("action_3")
        self.actionMake_Repo = QtWidgets.QAction(MainWindow)
        self.actionMake_Repo.setIcon(icon10)
        self.actionMake_Repo.setObjectName("actionMake_Repo")
        self.actionMake_Squashfs = QtWidgets.QAction(MainWindow)
        self.actionMake_Squashfs.setIcon(icon11)
        self.actionMake_Squashfs.setObjectName("actionMake_Squashfs")
        self.actionMake_Iso = QtWidgets.QAction(MainWindow)
        self.actionMake_Iso.setIcon(icon9)
        self.actionMake_Iso.setObjectName("actionMake_Iso")
        self.actionMake_Image = QtWidgets.QAction(MainWindow)
        self.actionMake_Image.setIcon(icon7)
        self.actionMake_Image.setObjectName("actionMake_Image")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuProject.addAction(self.actionUpdateRepo)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionRootImagePackages)
        self.menuProject.addAction(self.actionDesktopImagePackages)
        self.menuProject.addAction(self.actionLivecdImagePackages)
        self.menuProject.addAction(self.actionLanguages)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionMake_Repo)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionMake_Image)
        self.menuProject.addAction(self.actionMake_Squashfs)
        self.menuProject.addAction(self.actionMake_Iso)
        self.menuiso.addAction(self.actionMakeImage)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuiso.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineTitle, self.lineParameters)
        MainWindow.setTabOrder(self.lineParameters, self.lineRepository)
        MainWindow.setTabOrder(self.lineRepository, self.lineConfigFiles)
        MainWindow.setTabOrder(self.lineConfigFiles, self.linePluginPackage)
        MainWindow.setTabOrder(self.linePluginPackage, self.lineWorkFolder)
        MainWindow.setTabOrder(self.lineWorkFolder, self.comboType)
        MainWindow.setTabOrder(self.comboType, self.pushBrowseRepository)
        MainWindow.setTabOrder(self.pushBrowseRepository, self.pushBrowseConfigFiles)
        MainWindow.setTabOrder(self.pushBrowseConfigFiles, self.pushBrowsePluginPackage)
        MainWindow.setTabOrder(self.pushBrowsePluginPackage, self.pushBrowseWorkFolder)
        MainWindow.setTabOrder(self.pushBrowseWorkFolder, self.comboCompression)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pisiman"))
        self.pushBrowseRepository.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "Repository"))
        self.pushBrowseWorkFolder.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Image title"))
        self.lineRepository.setToolTip(_translate("MainWindow", "Local or remote URL of the repository index from which the image will be created"))
        self.pushBrowsePluginPackage.setText(_translate("MainWindow", "Browse"))
        self.label_6.setText(_translate("MainWindow", "Plugin package"))
        self.lineWorkFolder.setToolTip(_translate("MainWindow", "Path to the directory where Pardusman will work and create the related files and directories"))
        self.label_4.setText(_translate("MainWindow", "Config files"))
        self.comboCompression.setItemText(0, _translate("MainWindow", "xz"))
        self.comboCompression.setItemText(1, _translate("MainWindow", "gzip"))
        self.comboCompression.setItemText(2, _translate("MainWindow", "lzma"))
        self.comboCompression.setItemText(3, _translate("MainWindow", "lzo"))
        self.label_2.setText(_translate("MainWindow", "Work folder"))
        self.comboType.setItemText(0, _translate("MainWindow", "None"))
        self.comboType.setItemText(1, _translate("MainWindow", "Lxdm"))
        self.comboType.setItemText(2, _translate("MainWindow", "Lightdm"))
        self.comboType.setItemText(3, _translate("MainWindow", "Mdm"))
        self.comboType.setItemText(4, _translate("MainWindow", "Sddm"))
        self.lineParameters.setToolTip(_translate("MainWindow", "Extra parameters to pass to the kernel command line during boot."))
        self.lineTitle.setToolTip(_translate("MainWindow", "The title of the Pardus image"))
        self.label_7.setText(_translate("MainWindow", "Display Manager"))
        self.pushBrowseConfigFiles.setText(_translate("MainWindow", "Browse"))
        self.label_5.setText(_translate("MainWindow", "Extra parameters"))
        self.lineConfigFiles.setToolTip(_translate("MainWindow", "Path to the local directory config files"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuProject.setTitle(_translate("MainWindow", "Pro&ject"))
        self.menuiso.setTitle(_translate("MainWindow", "&Helper"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionOpen.setText(_translate("MainWindow", "&Open..."))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSaveAs.setText(_translate("MainWindow", "Sa&ve As..."))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionUpdateRepo.setText(_translate("MainWindow", "&Update Repo"))
        self.actionPackages.setText(_translate("MainWindow", "&Packages..."))
        self.actionRootImagePackages.setText(_translate("MainWindow", "&Root Image Packages..."))
        self.actionLanguages.setText(_translate("MainWindow", "La&nguages..."))
        self.actionMakeImage.setText(_translate("MainWindow", "Make &Image"))
        self.actionLivecdImagePackages.setText(_translate("MainWindow", "&Live Util Packages"))
        self.actionDesktopImagePackages.setText(_translate("MainWindow", "&Desktop Image Packages"))
        self.action.setText(_translate("MainWindow", "Ma&ke Repo"))
        self.action.setToolTip(_translate("MainWindow", "Create  only local repo "))
        self.action_2.setText(_translate("MainWindow", "Make &Squashfs"))
        self.action_2.setToolTip(_translate("MainWindow", "Make Only Squashfs Image"))
        self.action_3.setText(_translate("MainWindow", "Make &Iso"))
        self.action_3.setToolTip(_translate("MainWindow", "skip other steps"))
        self.actionMake_Repo.setText(_translate("MainWindow", "&Make Repo"))
        self.actionMake_Squashfs.setText(_translate("MainWindow", "Make &Squashfs"))
        self.actionMake_Iso.setText(_translate("MainWindow", "Ma&ke Iso"))
        self.actionMake_Image.setText(_translate("MainWindow", "Make &Image"))

import raw_rc
