# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/packages.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PackagesDialog(object):
    def setupUi(self, PackagesDialog):
        PackagesDialog.setObjectName("PackagesDialog")
        PackagesDialog.resize(714, 520)
        self.gridLayout_3 = QtWidgets.QGridLayout(PackagesDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(PackagesDialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeComponents = QtWidgets.QTreeWidget(self.layoutWidget)
        self.treeComponents.setSizeIncrement(QtCore.QSize(1, 0))
        self.treeComponents.setRootIsDecorated(False)
        self.treeComponents.setAllColumnsShowFocus(True)
        self.treeComponents.setHeaderHidden(False)
        self.treeComponents.setObjectName("treeComponents")
        self.treeComponents.header().setVisible(True)
        self.verticalLayout_2.addWidget(self.treeComponents)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchPackage = QtWidgets.QLineEdit(self.layoutWidget1)
        self.searchPackage.setObjectName("searchPackage")
        self.horizontalLayout.addWidget(self.searchPackage)
        self.comboFilter = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboFilter.setObjectName("comboFilter")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.horizontalLayout.addWidget(self.comboFilter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treePackages = QtWidgets.QTreeWidget(self.layoutWidget1)
        self.treePackages.setSizeIncrement(QtCore.QSize(3, 0))
        self.treePackages.setRootIsDecorated(False)
        self.treePackages.setAllColumnsShowFocus(True)
        self.treePackages.setObjectName("treePackages")
        self.verticalLayout.addWidget(self.treePackages)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelTotalSize = QtWidgets.QLabel(self.frame_2)
        self.labelTotalSize.setObjectName("labelTotalSize")
        self.gridLayout_2.addWidget(self.labelTotalSize, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(PackagesDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(PackagesDialog)
        QtCore.QMetaObject.connectSlotsByName(PackagesDialog)

    def retranslateUi(self, PackagesDialog):
        _translate = QtCore.QCoreApplication.translate
        PackagesDialog.setWindowTitle(_translate("PackagesDialog", "Packages"))
        self.treeComponents.setSortingEnabled(True)
        self.treeComponents.headerItem().setText(0, _translate("PackagesDialog", "Component"))
        self.comboFilter.setItemText(0, _translate("PackagesDialog", "All Packages"))
        self.comboFilter.setItemText(1, _translate("PackagesDialog", "Selected Packages"))
        self.comboFilter.setItemText(2, _translate("PackagesDialog", "Component Packages"))
        self.comboFilter.setItemText(3, _translate("PackagesDialog", "Component+ Packages"))
        self.treePackages.setSortingEnabled(True)
        self.treePackages.headerItem().setText(0, _translate("PackagesDialog", "Package"))
        self.treePackages.headerItem().setText(1, _translate("PackagesDialog", "Size"))
        self.treePackages.headerItem().setText(2, _translate("PackagesDialog", "Version"))
        self.treePackages.headerItem().setText(3, _translate("PackagesDialog", "Release"))
        self.labelTotalSize.setText(_translate("PackagesDialog", "0 MB"))
        self.label.setText(_translate("PackagesDialog", "Total Size:"))

